// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: k36LaA3jKH2iM5TPziRS5u
// Component: hTB0LhmAXD
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import SignUpPrompt from "../../SignUpPrompt"; // plasmic-import: jqelQqelLk2-/component
import "@plasmicapp/react-web/lib/plasmic.css";
import * as sty from "./PlasmicContactForm.module.css"; // plasmic-import: hTB0LhmAXD/css

export const PlasmicContactForm__VariantProps = new Array();

export const PlasmicContactForm__ArgProps = new Array();

function PlasmicContactForm__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <SignUpPrompt
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames("__wab_instance", sty.root)}
    />
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicContactForm__ArgProps,
      internalVariantPropNames: PlasmicContactForm__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicContactForm__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicContactForm";
  } else {
    func.displayName = `PlasmicContactForm.${nodeName}`;
  }
  return func;
}

export const PlasmicContactForm = Object.assign(
  // Top-level PlasmicContactForm renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicContactForm
    internalVariantProps: PlasmicContactForm__VariantProps,
    internalArgProps: PlasmicContactForm__ArgProps
  }
);

export default PlasmicContactForm;
/* prettier-ignore-end */
